// <auto-generated />
using System;
using AnimalZoo.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalZoo.App.Data.Migrations
{
    [DbContext(typeof(AnimalZooContext))]
    partial class AnimalZooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalZoo.App.Data.AnimalEnclosureAssignment", b =>
                {
                    b.Property<string>("AnimalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EnclosureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnimalId");

                    b.HasIndex("EnclosureName")
                        .HasDatabaseName("IX_Enclosures_EnclosureName");

                    b.ToTable("Enclosures", (string)null);
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Animal", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UniqueId");

                    b.HasIndex("AnimalType")
                        .HasDatabaseName("IX_Animals_AnimalType");

                    b.ToTable("Animals", (string)null);

                    b.HasDiscriminator<string>("AnimalType").HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Bat", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Bat");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Bird", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Bird");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Cat", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Dog", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Dog");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Eagle", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Eagle");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Fox", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Fox");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Lion", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Lion");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Monkey", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Monkey");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Parrot", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Parrot");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Penguin", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Penguin");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Raccoon", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Raccoon");
                });

            modelBuilder.Entity("AnimalZoo.App.Models.Turtle", b =>
                {
                    b.HasBaseType("AnimalZoo.App.Models.Animal");

                    b.HasDiscriminator().HasValue("Turtle");
                });

            modelBuilder.Entity("AnimalZoo.App.Data.AnimalEnclosureAssignment", b =>
                {
                    b.HasOne("AnimalZoo.App.Models.Animal", null)
                        .WithOne()
                        .HasForeignKey("AnimalZoo.App.Data.AnimalEnclosureAssignment", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
